### ISSUE TITLE
Karabiner config in karabiner.ts

### ISSUE THREAD

**Issue by evan-liu** [johnlindquist/dotfiles#2]
Hi John, first of all, thank you very much for your video on egghead.io which got me into Karabiner-Elements and Goku. Additionally, thank you for sharing your edn file here; I wish I had found it earlier.

To make the configuration more maintainable, I recently created a new project, [karabiner.ts](https://github.com/evan-liu/karabiner.ts). I wonder if I could fork this repository and write your configuration in TypeScript? This way, I would be able to get inspiration on more abstractions, like a `map('⇪').toSuperHyper()` (didn't know about super hyper). In the end, it would be great if you became interested in switching from Goku.

Once again, thank you very much for your videos (not only this one, but many others, even back in the Flash days, a few of which got me into using JetBrains IDEs).

**Comment by johnlindquist** [comment]
@evan-liu Please do! That sounds wonderful!

**Comment by evan-liu** [comment]
Thanks John, I've started [a PR on my fork](https://github.com/evan-liu/johnlindquist-dotfiles/pull/1/files) to track the progress (starting with `emoji-mode`) if you are interested at any time.
